### ISSUE TITLE
CF CLI plugin coloration does not gracefully degrade when piped

### ISSUE THREAD

**Issue by micahyoung** [cloudfoundry/cf-networking-release#10]
**Expected behavior:**
When I have an app named `node-1`
And one access rules for `node-1`
And I execute `cf list-access --app node-1`
Then I should see a list of access rules for my app with all strings `node-1` colorized
And I execute `cf list-access --app node-1 | less` (or other command that does not accept colors)
Then I should see a list of access rules for my app with no colorized strings
Ex:
```
Listing policies as myoung@pivotal.io...
OK

Source              Destination     Protocol        Port
node-1              node-2         tcp             9000
```

**Observed behavior:**
...
When I execute `cf list-access -app node-1 | less` 
Then I see all the control characters
Ex:
```
cf list-access --app node-1 | less
Listing policies as ESC[36;1mmyoung@pivotal.ioESC[0m...
ESC[32;1mOK
ESC[0m
ESC[;1mSource           Destination     Protocol        Port
ESC[0mESC[36;1mnode-1ESC[0m             ESC[36;1mnode-2ESC[0m           tcp             9000
```

**Notes**
For reference, it looks like `cf apps` degrades correctly. When I run `cf apps` or `cf apps | less` it is colorized and not, resp (with no extraneous characeters). I suspect the implementation may use the colorization library differently.

**Comment by rusha19** [comment]
Closing this issue, since CF networking commands are now in CF CLI.
