### ISSUE TITLE
Looking for a feature to inspect container inbound and outbound traffic

### ISSUE THREAD

**Issue by rbgigo** [cloudfoundry/cf-networking-release#17]
Hi 

I Know that CAP_NET_ADMIN capability - need to run tcpdump - has been removed from the Warden container in order to drastically reduce the attack surface. This is understood and makes sense to not let container users to execute privileged binaries like tcpdump.

We came to run tcpdump in a container to capture network traffic done in the context of troubleshooting sessions. It is a very convenient, none-intrusive, i.e. not requiring any configuration changes in an applications. Mostly we are not interested in the payload itself, we have only an interest in HTTP request and response headers.

Now from the exchange with the _cf-container-networking_ folks I learned that already today there is a solution that forwards packets outside of the container's network stack to a logging system. More specifically the first packet of every connection going out from the container is sent to the logging system.

Now I wonder whether it would be possible to enrich this capability in order that
* It is possible to define an IP address and port filter (source for inbound and destination for outbound)
* Allow use of event triggers, e.g. only start logging when a header arrives which has a certain value (regex)
* Both inbound and outbound packets or even only the HTTP headers should be forwarded to the logging system including the HTTP method and so on.

Your thoughts are appreciated very much
Regards
Ray

**Comment by rosenhouse** [comment]
I'm sorry about the much delayed response.  We don't have much to offer here at the moment, besides getting an operator to run `tcpdump` from the Diego cell host.

However, given the [current effort to integrate Istio & Envoy into Cloud Foundry](https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit#), you may be interested to read [this design doc from the Envoy community about adding an HTTP "tap" feature into Envoy](https://docs.google.com/document/d/1fgVAH8BMrq_5dt8m54Rxp0OGXt6WlNUsAW0xGlBOkJs/edit#heading=h.hmtvuhdteovz).  We could imagine enabling this feature in Cloud Foundry at some point in the future.

I'm going to close this issue for now.  But we can keep the conversation going here, and open a new issue when something real is within sight.

cc @rusha19 @shalako @shubhaat
