### ISSUE TITLE
Support TLS database connections for silk & policy-server

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/cf-networking-release#20]
As a platform operator
I want to be able to configure secure (TLS) database connections for the silk & policy-server
In order to be compliant to corporate security requirements.

Currently the silk & policy-server do not expose properties that would allow to configure secure database connectivity.

**Comment by bingosummer** [comment]
+1 for this feature.

**Comment by ameowlia** [comment]
Hi @x6j8x and @bingosummer, 

We've decided to split this out into two stories that you can follow here: 
- https://www.pivotaltracker.com/story/show/157300422
- https://www.pivotaltracker.com/story/show/157299862

Thanks, 
Amelia, CF Container Networking Team Member

**Comment by rosenhouse** [comment]
The latest [CF Networking](https://github.com/cloudfoundry/cf-networking-release/releases/tag/v2.2.0) and [Silk](https://github.com/cloudfoundry/silk-release/releases/tag/v2.2.0) Releases, version 2.2.0, include TLS support for MySQL databases.

Please let us know if try this out and have any feedback!
