### ISSUE TITLE
Possible issue with bbr unlock scripts

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-networking-release#23]
CAPI team was looking at your BBR scripts for inspiration and [this line](https://github.com/cloudfoundry/cf-networking-release/blob/193f31d064e7b3c39591048a04e6af1e6645b7a2/src/ctl-utils/ctl_util.sh#L22) in your unlock path jumped out. Should `echo 1` be `return 1` so that the exit code of the function is propagated back to the caller? Haven't noticed any issues running these scripts but figured I would give a heads up.

**Comment by chinangela** [comment]
Hi @ljfranklin, 

We do expect it to be an echo and not a return. We use this helper script in other job scripts, which require us to capture the value rather than exiting.

Thanks for reaching out still.

Cheers,
Angela and @adowns01
