### ISSUE TITLE
Update instructions to restage app after setting env variables

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry/cf-networking-release#28]
For the example app [cats-and-dogs](https://github.com/cloudfoundry/cf-networking-release/tree/develop/src/example-apps/cats-and-dogs) the user would need to restage the app after setting the env variables for the changes to apply to the app. 

Update instructions to read as follows by adding  `cf restage backend`:

```
cd cf-networking-release/src/example-apps/cats-and-dogs/backend
cf push backend --no-start
cf set-env backend CATS_PORTS "7007,7008"
cf set-env backend UDP_PORTS "9003,9004"
cf restage backend
cf start backend
```

**Comment by chinangela** [comment]
Hi @shubhaat ,

While the cf cli gives a tip to restage your app, when you use `--no-start`, it removes the need to restage as the app was never started.

Cheers,
Angela and @adowns01
