### ISSUE TITLE
CustomIPTablesCompatibilityTest should be skipped by default

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-networking-release#33]
After bumping to master of the latest cf-networking-release acceptance tests, we see the following failure:

```
Custom iptables compatibility
/tmp/build/29505db7/acceptance-tests/src/test/acceptance/custom_iptables_compatibility_test.go:15
  when a custom iptables rule is added and a new app is pushed
  /tmp/build/29505db7/acceptance-tests/src/test/acceptance/custom_iptables_compatibility_test.go:42
    still applies the iptable rule to the new app [It]
    /tmp/build/29505db7/acceptance-tests/src/test/acceptance/custom_iptables_compatibility_test.go:43

    No future change is possible.  Bailing out early after 0.000s.
    Expected
        <int>: 7
    to match exit code:
        <int>: 0

    /tmp/build/29505db7/acceptance-tests/src/test/acceptance/custom_iptables_compatibility_test.go:46
```

The underlying error was `curl: (7) Failed to connect to 10.0.4.36 port 8898: Connection refused`. It sounds like this test will only pass is a [certain release](https://cloudfoundry.slack.com/archives/C0JV2NPJ4/p1518456820000144) is co-located on the cell listening on port 8898.

As this test will not pass against a standard CF deployment, could `SkipCustomIPTablesCompatibilityTest` be set to `true` by default?

**Comment by chinangela** [comment]
Hi @ljfranklin ,

We have changed the property to `RunCustomIPTablesCompatibilityTest` so users will need to explicitly opt-in to running it. See: 068663917e87fd8f56cb3edd8593b9d6dcfaa9f5

Cheers,
Angela
