### ISSUE TITLE
Handle CORS calls

### ISSUE THREAD

**Issue by samu** [cloudfoundry/cf-networking-release#34]
## Issue

It should be possible to target the `/networking` endpoints via a browser. When doing so, a browser will first check CORS by issuing a preflight request. These requests fail with a 405 status code.

## Steps to Reproduce

Make an http request to `/networking/v1/external/policies` using the OPTIONS method (this simulates the preflight request which is performed by browsers by default).

## Expected result

Response with 200 status code.

## Current result

Response with 405 status code (Method Not Allowed)

**Comment by adobley** [comment]
I have created a feature, based off the investigation above, in Pivotal Tracker so we can manage this:

https://www.pivotaltracker.com/n/projects/1498342/stories/155609306

**Comment by christianang** [comment]
Hi @samu,

This has been finished in https://github.com/cloudfoundry/cf-networking-release/releases/tag/v1.13.0.

I'll be closing this issue, but reopen and let us know if you have any issues.

Thanks,
Christian and Aidan
