### ISSUE TITLE
Allowing networking tests to run in parallel with CF acceptance tests

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-networking-release#36]
Currently we have to run the nats suite after the cats suite due to nats messing with global settings like running ASGs: https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/test/acceptance/external_connectivity_test.go. Could this test instead use ASGs scoped to a given org to avoid test pollution?

This has previously bitten our team as we started by running cats and nats in parallel and only later discovered this introduced flakiness due to changing global ASGs.

**Comment by chinangela** [comment]
Hi @ljfranklin,

Unfortunately, default cf-deployment allows applications to connect to all public networks as a global ASG. In order to test the removing ASGs ensures applications cannot talk to an external entity, we must remove this ASG.

If you have suggestions for other ways to test, we are more than open to a discussion. Currently, in CATs, we have to test based on exit codes (which is pretty gross and differs depending on network implementation).

Cheers,
Angela

**Comment by ljfranklin** [comment]
@chinangela How important is the "external" part of this test? If the goal is to test that ASGs work, the user could pass in a "secure address", e.g. "10.0.0.6:80", which is what WATs does. This address should be unreachable under the default rules, but the test suite adds a rule that allows it and verifies connectivity succeeds.

**Comment by ljfranklin** [comment]
On the subject of CATs, has there been talk of moving some of the NATs tests into CATs? I know the WATs team just rolled their tests into CATs which allowed us to remove a few CI tasks around running an extra test suite, would be cool if other CF test suites followed.

**Comment by chinangela** [comment]
Hi @ljfranklin,

Can you point me to the specific WATs test?

We are currently in the process of merging the happy path cases of CNATs into CATs, but this test suite will remain for edge cases we think are important.

**Comment by chinangela** [comment]
Thanks @ljfranklin ! 

We've made a PR to have our ASG test do the same thing as WATs (changing `WindowsSecureAddress` to `SecureAddress`). 

As far as recommendation for continuing to run NATs in the pipeline after these PRs are accepted-- I wouldn't want to make a recommendation alone. We'll be talking about it as a team at retro tomorrow, and we'll let you know our team's recommendation.

**Comment by ljfranklin** [comment]
> We've made a PR to have our ASG test...

Nice, thanks for making that change! 

> we'll let you know our team's recommendation.

Cool, keep us in the loop.

**Comment by chinangela** [comment]
Hi @ljfranklin.

We think it's fine to not run NATs if y'all don't want to.

I think this answers all of your questions, so I'm closing the issue. Feel free to open it though if you have more.
