### ISSUE TITLE
Post-start script in job "policy-server" and "policy-server-internal" failed when deploying CF

### ISSUE THREAD

**Issue by norshtein** [cloudfoundry/cf-networking-release#44]
## Issue

When deploying CF, the bosh director reported an error complaining the post-start script failed in job "policy-server" and "policy-server-internal": 

> Task 28 | 23:03:51 | Updating instance api: api/45b53d96-d781-47cd-984c-2d49d9718077 (0) (canary) (00:05:32)
>                    L Error: Action Failed get_task: Task e66171d7-d403-4900-7eeb-03bb7e05167c result: 2 of 3 post-start scripts failed. Failed Jobs: policy-server, policy-server-internal. Successful Jobs: cloud_controller_ng.
> Task 28 | 23:04:48 | Updating instance uaa: uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7 (1) (00:02:45)
> Task 28 | 23:04:48 | Error: Action Failed get_task: Task e66171d7-d403-4900-7eeb-03bb7e05167c result: 2 of 3 post-start scripts failed. Failed Jobs: policy-server, policy-server-internal. Successful Jobs: cloud_controller_ng.

## Context

I'm deploying CF on Azure, using [azure-quick-start-template](https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup), the CF manifest version is [v2.2.0](https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/manifests/cf-deployment.yml)

## Steps to Reproduce

The issue is likely to be occasional, I have deployed CF on Azure for many times, only get this error twice.

## Expected result

The CF should be deployed successfully.

## Current result

The bosh director reported the error with following running log:

> Task 28
> 
> Task 28 | 22:00:06 | Preparing deployment: Preparing deployment (00:00:11)
> Task 28 | 22:00:28 | Preparing package compilation: Finding packages to compile (00:00:00)
> Task 28 | 22:00:29 | Creating missing vms: consul/a9cb4f16-d318-4876-940d-e7e52114209d (2)
> Task 28 | 22:00:29 | Creating missing vms: api/07666b3c-74e2-4838-8b8d-82ecd8de7e02 (1)
> Task 28 | 22:00:29 | Creating missing vms: consul/5a183dcf-0d63-44e6-a18c-5d319126c680 (0)
> Task 28 | 22:00:29 | Creating missing vms: consul/f6f4bfea-2c77-4d17-8c6b-da85f518dbf7 (1)
> Task 28 | 22:00:29 | Creating missing vms: adapter/e58e9f9d-176c-4184-a65c-dbd4a585547f (0)
> Task 28 | 22:00:29 | Creating missing vms: diego-api/81a18f7f-63c8-4fa4-865c-6e003b7a4006 (1)
> Task 28 | 22:00:29 | Creating missing vms: uaa/33fc6f70-27ba-4f65-b349-24751ebb4368 (0)
> Task 28 | 22:00:29 | Creating missing vms: uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7 (1)
> Task 28 | 22:00:29 | Creating missing vms: router/b929e53b-fcb6-4d6e-8ca8-936f705ea572 (0)
> Task 28 | 22:00:29 | Creating missing vms: diego-api/8cfbefe1-4b52-4293-99f5-808f7ec40c7c (0)
> Task 28 | 22:00:29 | Creating missing vms: adapter/00bed6a8-acad-46ea-9f8a-2430e81fc128 (1)
> Task 28 | 22:00:29 | Creating missing vms: diego-cell/a760ec90-a4e1-4b27-a686-ea615d15e4ad (0)
> Task 28 | 22:00:29 | Creating missing vms: tcp-router/b59178ed-160f-4c0d-af0f-07acf0df9e32 (1)
> Task 28 | 22:00:29 | Creating missing vms: doppler/435d8a37-817b-4adb-b1f7-f2c91c172a0f (0)
> Task 28 | 22:00:29 | Creating missing vms: scheduler/0588f7ff-5131-4dec-a626-7919a800dfbe (1)
> Task 28 | 22:00:29 | Creating missing vms: nats/709a90fa-9bfb-46dd-803f-631e76524835 (0)
> Task 28 | 22:00:29 | Creating missing vms: scheduler/42a0f771-1ca9-4e3c-8e99-67b3c05bcc18 (0)
> Task 28 | 22:00:29 | Creating missing vms: doppler/b54673df-3e68-4536-bacb-91f5c9fa32cb (1)
> Task 28 | 22:00:29 | Creating missing vms: router/efb756e2-922e-4d74-97a3-d910cb03f9f1 (1)
> Task 28 | 22:00:29 | Creating missing vms: cc-worker/5735938a-ffe7-4e03-a67e-ab8908794dab (1)
> Task 28 | 22:00:29 | Creating missing vms: diego-cell/c27c2575-5f85-4760-b262-a4231deb29b8 (1)
> Task 28 | 22:00:29 | Creating missing vms: database/531e17be-a0ed-4409-99f6-4ccb4e948b58 (0)
> Task 28 | 22:00:29 | Creating missing vms: log-api/8e3f8ffc-df1c-464a-960c-275ef412718f (0)
> Task 28 | 22:00:29 | Creating missing vms: cc-worker/32cd1d01-051a-4e34-91e7-fa840fb64c83 (0)
> Task 28 | 22:00:29 | Creating missing vms: tcp-router/46415b07-5a38-45ab-84ab-3886471f7245 (0)
> Task 28 | 22:00:29 | Creating missing vms: doppler/948b4f21-e382-4204-84a5-d797662d8da0 (2)
> Task 28 | 22:00:29 | Creating missing vms: log-api/3f7eaf7f-9a99-4697-bd6d-fcf3612ca647 (1)
> Task 28 | 22:00:29 | Creating missing vms: doppler/a54e1be3-e5c1-46c6-9041-f40e5a4dd792 (3)
> Task 28 | 22:00:29 | Creating missing vms: nats/4efa1a74-1437-4651-bdf5-643031c0a879 (1)
> Task 28 | 22:00:29 | Creating missing vms: api/45b53d96-d781-47cd-984c-2d49d9718077 (0)
> Task 28 | 22:04:44 | Creating missing vms: uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7 (1) (00:04:15)
> Task 28 | 22:04:46 | Creating missing vms: api/45b53d96-d781-47cd-984c-2d49d9718077 (0) (00:04:17)
> Task 28 | 22:05:08 | Creating missing vms: database/531e17be-a0ed-4409-99f6-4ccb4e948b58 (0) (00:04:39)
> Task 28 | 22:05:09 | Creating missing vms: doppler/b54673df-3e68-4536-bacb-91f5c9fa32cb (1) (00:04:40)
> Task 28 | 22:05:09 | Creating missing vms: uaa/33fc6f70-27ba-4f65-b349-24751ebb4368 (0) (00:04:40)
> Task 28 | 22:05:16 | Creating missing vms: api/07666b3c-74e2-4838-8b8d-82ecd8de7e02 (1) (00:04:47)
> Task 28 | 22:05:19 | Creating missing vms: adapter/e58e9f9d-176c-4184-a65c-dbd4a585547f (0) (00:04:50)
> Task 28 | 22:05:22 | Creating missing vms: diego-api/81a18f7f-63c8-4fa4-865c-6e003b7a4006 (1) (00:04:53)
> Task 28 | 22:05:23 | Creating missing vms: doppler/948b4f21-e382-4204-84a5-d797662d8da0 (2) (00:04:54)
> Task 28 | 22:05:26 | Creating missing vms: doppler/a54e1be3-e5c1-46c6-9041-f40e5a4dd792 (3) (00:04:57)
> Task 28 | 22:05:27 | Creating missing vms: consul/5a183dcf-0d63-44e6-a18c-5d319126c680 (0) (00:04:58)
> Task 28 | 22:05:28 | Creating missing vms: consul/a9cb4f16-d318-4876-940d-e7e52114209d (2) (00:04:59)
> Task 28 | 22:05:29 | Creating missing vms: scheduler/0588f7ff-5131-4dec-a626-7919a800dfbe (1) (00:05:00)
> Task 28 | 22:05:30 | Creating missing vms: nats/709a90fa-9bfb-46dd-803f-631e76524835 (0) (00:05:01)
> Task 28 | 22:05:30 | Creating missing vms: diego-cell/c27c2575-5f85-4760-b262-a4231deb29b8 (1) (00:05:01)
> Task 28 | 22:05:30 | Creating missing vms: consul/f6f4bfea-2c77-4d17-8c6b-da85f518dbf7 (1) (00:05:01)
> Task 28 | 22:05:31 | Creating missing vms: diego-cell/a760ec90-a4e1-4b27-a686-ea615d15e4ad (0) (00:05:02)
> Task 28 | 22:05:32 | Creating missing vms: diego-api/8cfbefe1-4b52-4293-99f5-808f7ec40c7c (0) (00:05:03)
> Task 28 | 22:05:33 | Creating missing vms: tcp-router/b59178ed-160f-4c0d-af0f-07acf0df9e32 (1) (00:05:04)
> Task 28 | 22:05:33 | Creating missing vms: adapter/00bed6a8-acad-46ea-9f8a-2430e81fc128 (1) (00:05:04)
> Task 28 | 22:05:33 | Creating missing vms: log-api/3f7eaf7f-9a99-4697-bd6d-fcf3612ca647 (1) (00:05:04)
> Task 28 | 22:05:33 | Creating missing vms: nats/4efa1a74-1437-4651-bdf5-643031c0a879 (1) (00:05:04)
> Task 28 | 22:05:33 | Creating missing vms: tcp-router/46415b07-5a38-45ab-84ab-3886471f7245 (0) (00:05:04)
> Task 28 | 22:05:43 | Creating missing vms: doppler/435d8a37-817b-4adb-b1f7-f2c91c172a0f (0) (00:05:14)
> Task 28 | 22:05:43 | Creating missing vms: log-api/8e3f8ffc-df1c-464a-960c-275ef412718f (0) (00:05:14)
> Task 28 | 22:05:44 | Creating missing vms: cc-worker/5735938a-ffe7-4e03-a67e-ab8908794dab (1) (00:05:15)
> Task 28 | 22:05:48 | Creating missing vms: cc-worker/32cd1d01-051a-4e34-91e7-fa840fb64c83 (0) (00:05:19)
> Task 28 | 22:07:18 | Creating missing vms: router/b929e53b-fcb6-4d6e-8ca8-936f705ea572 (0) (00:06:49)
> Task 28 | 22:08:07 | Creating missing vms: router/efb756e2-922e-4d74-97a3-d910cb03f9f1 (1) (00:07:38)
> Task 28 | 22:33:51 | Creating missing vms: scheduler/42a0f771-1ca9-4e3c-8e99-67b3c05bcc18 (0) (00:33:22)
> Task 28 | 22:33:53 | Updating instance consul: consul/5a183dcf-0d63-44e6-a18c-5d319126c680 (0) (canary) (00:05:45)
> Task 28 | 22:39:38 | Updating instance consul: consul/f6f4bfea-2c77-4d17-8c6b-da85f518dbf7 (1) (00:04:35)
> Task 28 | 22:44:13 | Updating instance consul: consul/a9cb4f16-d318-4876-940d-e7e52114209d (2) (00:05:20)
> Task 28 | 22:49:33 | Updating instance adapter: adapter/e58e9f9d-176c-4184-a65c-dbd4a585547f (0) (canary)
> Task 28 | 22:49:33 | Updating instance nats: nats/709a90fa-9bfb-46dd-803f-631e76524835 (0) (canary) (00:00:49)
> Task 28 | 22:50:22 | Updating instance adapter: adapter/e58e9f9d-176c-4184-a65c-dbd4a585547f (0) (canary) (00:00:49)
> Task 28 | 22:50:22 | Updating instance nats: nats/4efa1a74-1437-4651-bdf5-643031c0a879 (1)
> Task 28 | 22:50:22 | Updating instance adapter: adapter/00bed6a8-acad-46ea-9f8a-2430e81fc128 (1) (00:00:26)
> Task 28 | 22:50:48 | Updating instance nats: nats/4efa1a74-1437-4651-bdf5-643031c0a879 (1) (00:00:26)
> Task 28 | 22:50:48 | Updating instance database: database/531e17be-a0ed-4409-99f6-4ccb4e948b58 (0) (canary) (00:06:14)
> Task 28 | 22:57:02 | Updating instance diego-api: diego-api/8cfbefe1-4b52-4293-99f5-808f7ec40c7c (0) (canary) (00:00:51)
> Task 28 | 22:57:53 | Updating instance diego-api: diego-api/81a18f7f-63c8-4fa4-865c-6e003b7a4006 (1) (00:00:26)
> Task 28 | 22:58:19 | Updating instance cc-worker: cc-worker/32cd1d01-051a-4e34-91e7-fa840fb64c83 (0) (canary)
> Task 28 | 22:58:19 | Updating instance uaa: uaa/33fc6f70-27ba-4f65-b349-24751ebb4368 (0) (canary)
> Task 28 | 22:58:19 | Updating instance api: api/45b53d96-d781-47cd-984c-2d49d9718077 (0) (canary)
> Task 28 | 23:02:03 | Updating instance uaa: uaa/33fc6f70-27ba-4f65-b349-24751ebb4368 (0) (canary) (00:03:44)
> Task 28 | 23:02:03 | Updating instance uaa: uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7 (1)
> Task 28 | 23:02:09 | Updating instance cc-worker: cc-worker/32cd1d01-051a-4e34-91e7-fa840fb64c83 (0) (canary) (00:03:50)
> Task 28 | 23:02:09 | Updating instance cc-worker: cc-worker/5735938a-ffe7-4e03-a67e-ab8908794dab (1) (00:00:34)
> Task 28 | 23:03:51 | Updating instance api: api/45b53d96-d781-47cd-984c-2d49d9718077 (0) (canary) (00:05:32)
>                    L Error: Action Failed get_task: Task e66171d7-d403-4900-7eeb-03bb7e05167c result: 2 of 3 post-start scripts failed. Failed Jobs: policy-server, policy-server-internal. Successful Jobs: cloud_controller_ng.
> Task 28 | 23:04:48 | Updating instance uaa: uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7 (1) (00:02:45)
> Task 28 | 23:04:48 | Error: Action Failed get_task: Task e66171d7-d403-4900-7eeb-03bb7e05167c result: 2 of 3 post-start scripts failed. Failed Jobs: policy-server, policy-server-internal. Successful Jobs: cloud_controller_ng.
> 
> Task 28 Started  Fri Jun 29 22:00:06 UTC 2018
> Task 28 Finished Fri Jun 29 23:04:48 UTC 2018
> Task 28 Duration 01:04:42
> Task 28 error
> 
> Updating deployment:
>   Expected task '28' to succeed but state is 'error'
> 
> Exit code 1
> 

I run `monit summary` in VM `api/45b53d96-d781-47cd-984c-2d49d9718077` and get:

> Process 'consul_agent'              running
> Process 'cloud_controller_ng'       running
> Process 'cloud_controller_worker_local_1' running
> Process 'cloud_controller_worker_local_2' running
> Process 'nginx_cc'                  running
> Process 'route_registrar'           running
> Process 'statsd_injector'           running
> Process 'file_server'               running
> Process 'routing-api'               running
> Process 'policy-server'             not monitored
> Process 'policy-server-internal'    Connection failed
> Process 'cc_uploader'               running
> Process 'loggregator_agent'         running
> System 'system_localhost'           running
> 

Log `/var/vcap/sys/log/policy-server/post-start.stderr.log` in VM `api/45b53d96-d781-47cd-984c-2d49d9718077`:

> \+ source /var/vcap/packages/networking-ctl-utils/ctl_util.sh
> \+ export URL=127.0.0.1:4002
> \+ URL=127.0.0.1:4002
> \+ export TIMEOUT=25
> \+ TIMEOUT=25
> ++ wait_for_server_to_become_healthy 127.0.0.1:4002 25
> ++ local url=127.0.0.1:4002
> ++ local timeout=25
> +++ seq 25
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4002
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4002
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ......
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4002
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4002
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ echo 1
> \+ exit 1
> 

Log `/var/vcap/sys/log/policy-server-internal/post-start.stderr.log` in VM `api/45b53d96-d781-47cd-984c-2d49d9718077`:

> \+ source /var/vcap/packages/networking-ctl-utils/ctl_util.sh
> \+ export URL=127.0.0.1:4003
> \+ URL=127.0.0.1:4003
> \+ export TIMEOUT=25
> \+ TIMEOUT=25
> ++ wait_for_server_to_become_healthy 127.0.0.1:4003 25
> ++ local url=127.0.0.1:4003
> ++ local timeout=25
> +++ seq 25
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4003
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4003
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ......
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4003
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ for _ in '$(seq "${timeout}")'
> ++ set +e
> ++ curl -f --connect-timeout 1 127.0.0.1:4003
> ++ '[' 7 -eq 0 ']'
> ++ set -e
> ++ sleep 1
> ++ echo 1
> \+ exit 1

Log `/var/vcap/sys/log/policy-server/policy-server.stderr.log` in VM `api/45b53d96-d781-47cd-984c-2d49d9718077`:

> ......
> 2018/07/02 03:21:34 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:22:44 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:23:54 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:25:04 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:26:14 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:27:24 cfnetworking.policy-server: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2

Log `/var/vcap/sys/log/policy-server-internal/policy-server-internal.stderr.log` in VM `api/45b53d96-d781-47cd-984c-2d49d9718077`:
> ......
> 2018/07/02 03:23:14 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:24:25 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:25:34 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:26:45 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:27:54 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 2018/07/02 03:29:05 cfnetworking.policy-server-internal: failed to construct datastore: perform migrations: executing migration: Error 1060: Duplicate column name 'start_port' handling 2
> 

It seems these two errors are caused by curl failure, so I run curl manually and get:
```
api/45b53d96-d781-47cd-984c-2d49d9718077:/var/vcap/data/sys/log/policy-server-internal# curl -f --connect-timeout 1 127.0.0.1:4002

curl: (7) Failed to connect to 127.0.0.1 port 4002: Connection refused

api/45b53d96-d781-47cd-984c-2d49d9718077:/var/vcap/data/sys/log/policy-server-internal# curl -f --connect-timeout 1 127.0.0.1:4003

curl: (7) Failed to connect to 127.0.0.1 port 4003: Connection refused
```

I think there should be two services listening on port 4002 and 4003, but for some reason they are not here. Could you have a look on the issue? Besides, I have two questions:
- There are two api instance in the cluster, why only one is reported to be failing? I run `bosh -e azure -d cf vms` and get:
```
Instance                                         Process State  AZ  IPs        VM CID                                                                                                                                               VM Type        Active
api/07666b3c-74e2-4838-8b8d-82ecd8de7e02         running        z2  10.0.0.19  agent_id:eaa20d34-a50e-436f-8747-2009016c1ebb;resource_group_name:myrg;storage_account_name:mysa                            small        true
api/45b53d96-d781-47cd-984c-2d49d9718077         failing        z1  10.0.0.18  agent_id:271b035c-2feb-4288-9fc0-2102aef9c44d;resource_group_name:myrg;storage_account_name:mysa                             small          true
```
And I logged into another api instance reported to be `running`, and the folder `/var/vcap/sys/log` is empty. What happened?

- The uaa instance doesn't have job `policy-server` and `policy-server-internal`, why bosh director report that the error also happens in uaa instance? I run `monit summary` in VM `uaa/c3d7b74e-7be8-42e2-beb4-1f4031306ce7` and find the uaa instance doesn't have job `policy-server` and `policy-server-internal` :

> Process 'consul_agent'              running
> Process 'uaa'                       running
> Process 'route_registrar'           running
> Process 'statsd_injector'           running
> Process 'loggregator_agent'         running
> System 'system_localhost'           running

**Comment by christianang** [comment]
Hi @norshtein,

We recently cut a v2.7.0 of cf-networking-release that increases the timeout of post-start because other component teams have also noticed that post-start intermittently fails and I believe you might be running into the same issue. The issue being that the policy server can take more than 25 seconds (the timeout of post-start) to start. Looking at the log timestamps the migration errors seem to be from a while ago so they are probably not part of the problem.

It should be in the next release of `cf-deployment` if you want to wait for that otherwise I would bump cf-networking-release in your manifest to v2.7.0.

As for why one vm says it is running. BOSH reports the VMs current status, even if all it has done is start a VM without adding the jobs to it yet, which is admittedly a little confusing.

**Comment by norshtein** [comment]
Hi @christianang , thank you for the explanation, we will wait for the next release of `cf-deployment`.

**Comment by norshtein** [comment]
Hi @christianang , we encountered this error again, the content of the error log is similar but is longer than previous one. At the end of log `api/2fb604ae-0add-468e-be75-d1db13feafaa:/var/vcap/data/sys/log/policy-server/post-start.stderr.log`, there is one line: `echo 'policy server failed to start within 120 seconds'`. And at the end of log `/var/vcap/data/sys/log/policy-server-internal/post-start.stderr.log`, there is one line: `echo 'policy server internal failed to start within 120 seconds'`. I think 120 seconds is enough for starting policy server, could you have a look on this issue again?

**Comment by christianang** [comment]
Hi @norshtein,

Are there any errors inside the `policy-server.stdout.log`? Presumably the policy-server didn't start within 120 seconds because the policy server failed for some reason. Or is it getting the same error that happened originally? E.g `executing migration: Error 1060: Duplicate column name 'start_port' handling 2`.

We have seen issues with the policy-server handling migrations and depending on how a migration failed it could get into a state where it will never pass the migration without modifying the database.

We have recently added some mitigations for migrations around multiple migrations running at the same time (due to it happening on every vm on start). In the latest release it will only happen once per deploy in pre-start on the bootstrap node.

**Comment by christianang** [comment]
Looks like one of the migrations failed in the middle, which borks the migration process. If this environment doesn't need to be kept around you can delete the deployment, freshly deploy it, and hope that it passes the migration. This is a known flaky bug. Unfortunately, the way the migrations are built right now we can't change older migrations that have the possibility of borking the migration process.

If you want to keep the foundation around you would need to alter the table to delete the `type` column on the group table and redeploy to start the migration process again.

**Comment by norshtein** [comment]
Hi @christianang , what does "migration" mean? I'm running a new CF deployment and don't have an old environment, so I don't have anything need to migrate from old environment to new environment. And will this flaky bug be fixed later?

**Comment by christianang** [comment]
@norshtein the way the policy server works now it does a "migration" even on fresh deploys. It essentially plays through all the migrations since the beginning to get to the latest schema.

The good news is we have been working on a solution that we hope will help mitigate the issue or at least if it happens again it doesn't put your database into a borked state that requires manual intervention. I'll let you know when we get a new release out with the mitigation for you to test.

**Comment by christianang** [comment]
@norshtein we cut a new release of cf-networking that includes the mitigations for our migrations. It doesn't prevent migrations from failing, but if it does fail it should be able to retry and succeed without manual intervention. Let me know if you continue having issues.

**Comment by christianang** [comment]
I'm going to close the issue now, but if you still have migration issues with the new version let us know.
