### ISSUE TITLE
Documentation: Internal domain

### ISSUE THREAD

**Issue by WalterS** [cloudfoundry/cf-networking-release#52]
## Issue
From the [documentation](https://github.com/cloudfoundry/cf-networking-release/blob/0f9b816ef38bd9b1eed24f4542a5fa1b4966a99a/docs/app-sd.md#configuring-custom-internal-domains) it is not clear why and when to use a trailing dot for the internal domain name.

**Comment by christianang** [comment]
I've updated the documentation. Thanks for bringing it up.
