### ISSUE TITLE
policy cleanup is broken - cc_client space iteration doesn't work

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/cf-networking-release#57]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

One of our teams hit the MaxPolicyPerAppSource limit and was wondering why. 

The we found this in our logs:

policy-server.stdout.log:{"timestamp":"2018-11-05T22:48:36.637458246Z","level":"error","source":"cfnetworking.policy-server","message":"cfnetworking.policy-server.policy-cleaner-poller.poll-cycle","data":{"error":"get live space guids failed: json client do: http client do: Get https://cloud-controller-ng.service.cf.internal:9024https//api.sys.*/v3/spaces?page=2\u0026per_page=50: invalid URL port \"9024https\"","session":"4"}}

Pagination seems to be broken for spaces as this (https://github.com/cloudfoundry/cf-networking-release/blob/12dee0866047fc94184f14bcd37c0bf6af0b0ac2/src/policy-server/cc_client/client.go#L172) returns a fully-qualified URL which is then appended to the base url by the JSON client.

As a workaround we will increase the limit for now to get our teams working again. 

Please fix.

**Comment by christianang** [comment]
Thanks for bringing this up. We fixed it and it will be in the next release of cf-networking-release. 💯
