### ISSUE TITLE
CF App SD docs lacks explanation on new Functionality/components

### ISSUE THREAD

**Issue by iamejboy** [cloudfoundry/cf-networking-release#58]
## Issue

CF App SD docs lacks explanation on new Functionality/component . We can only see Architecture diagram of data flow [here](https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/app-sd.md#architecture) but does not explain what/how it works.

## Expected result

It would be better if we could have a more detailed documentation explaining the Architecture diagram, how it works, what's the new functionality/component  adds/do/function ?

**Comment by tylerschultz** [comment]
Hi @iamejboy, we've updated the documentation on the develop branch, which can be viewed here: https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/app-sd.md#architecture

Let us know if you think there's something we can expand on.

**Comment by iamejboy** [comment]
@tylerschultz thanks for providing more info. This helps a lot.
