### ISSUE TITLE
Applications crash during update in large deployments

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-networking-release#61]
## Issue

In a large deployment with 1000 cells (will likely also appear with less cells), during an update we encountered that apps crash due the fact that during container creation the `policy-server-internal` gets overloaded and requests from the `vxlan-policy-agent` time out.

## Context

During an update with 1000 cells we saw that multiple hundred and in another scenario even thousands of apps crashed. When apps getting drained to a different cell/on container creation they request the `policies` from the `policy-server-internal`. This will overload the `policy-server-internal` and leads to timeouts since a lot of requests are issued at the same time => apps crashes

## Steps to Reproduce

We have a landscape with 1000 cells (`max_in_flight` set to 50) and 30k apps. We created 4k policies. When deleting all policies the same issue did not occur since probably the database queries are much faster.

We set the [policy_poll_interval_seconds](https://github.com/cloudfoundry/silk-release/blob/b806a1b3cff82907b1b8b6373d11861d5f2f2049/jobs/vxlan-policy-agent/spec#L42-L44) to 300, otherwise the `policy-server-internal` would be constantly overloaded. With this configuration the landscape seems stable (outside of an update).

## Expected result

No app crashes during update

## Current result

Request times out during container creation:

```
{"timestamp":"2018-12-04T16:16:43.381785739Z","level":"error","source":"guardian","message":"guardian.create.external-networker-result","data":{"action":"up","error":"exit status 1","handle":"27921ba0-afe9-4653-6dbb-d1ab","session":"6274","stderr":"cfnetworking: cni up failed: add network list failed: vpa response code: 500 with message: failed to force policy p
oll cycle: get-rules: failed to get policies: http client do: Get https://policy-server.service.cf.internal:4003/networking/v1/internal/policies?id=00ee43e2-cb6b-4bce-8b3d-34af44a4519b,e06649ce-40b7-40b3-8f83-339a832a44a7,83119d81-6269-410c-9c7e-6b0b5cfc2997,313261ae-4107-4f3a-8a99-5c63c2bc157c,165aebcb-cd59-4ab7-829f-a87b08642329,2207420e-9e14-4979-8c3d-eb1f0f8
4d25d,2237cfe8-cf0f-469c-b9cb-84fa8be75be2,61f88739-5ea3-40b7-8ba3-36100bf8665e,1d08fca4-5a11-44d4-85e4-90233fccd976,d5afd404-a250-4b59-8c38-106c765ebf06,2d105c1c-6aff-4f09-b83d-00550fac6245,b206bdb8-23fb-4d90-8a8c-24e2f6c6c4e9,fd886474-47ee-4709-8b06-1c88c954dfb5,75f1693d-7884-424a-9dba-ca09202a2eed,cb121d69-f5e9-4310-8d19-c636d528916f,5fa65bbe-ecea-4acd-8cb5-b
70ef56f87c5,6f3a12c9-b190-4ab8-b677-2786fff7abed,077a31a8-3925-4818-b42e-11adf7ad8772,d590b654-e32d-4f1b-985b-323daf349fb5,8045de6f-97fc-4df9-a964-12f06a4ffb2f,a229c94e-bad5-48e3-99c6-4ffa3df0eff6,03d19d9c-928f-48f6-b099-ce3cb36bc36c,a825d1e0-472e-425c-9bd6-4a344ef8b497,9d27ec24-084c-4b3a-b6dc-36c99807feab,9c31c071-6e28-4678-b8f3-653687e7ca0b,b1bf32c1-a9de-48d6-
8318-e2089ce15ce5,28d5b6a8-bd9b-4099-be30-a446133b0695,147a1af4-5a6c-48df-92b1-553c6585b21d,80ceb97e-5525-443b-8f39-dc785fd1a00d,fcba7369-eae4-4dac-9292-d3f706577472,48d694c2-dd3a-4c14-a09d-58ee14785d23,d31e5d50-5b65-4805-a45b-7e08c0f98e2c,370d95f2-29d0-4d0c-9f16-580be271d688,6aa1a0da-77ab-4669-a87d-27cb40e3dffa,fe326b2e-5b96-4b17-a98a-8e3f8faec489,d0fbf238-09a7
-41ae-8076-3ecd4d6cd4bd,c7c23786-6d46-4eb2-857c-5213564125c7,7ad92303-f5a4-42ba-b98e-0ebaa09daa2b,7b9dcad8-c6ce-485c-9a32-0e51af27f022,51cefe4b-ded6-4f36-9fc1-a6494fe45ae9,2ba95e1a-0b54-4dfe-862e-6be8cbaaccfd,1ec92530-84cd-4244-8414-073c63e9fd64,e1b1974c-ac2f-42f2-ba7d-1d128736ef28,2a1fbd35-6ec2-4cdf-99e3-65968c89a398,f40d6531-b263-43e9-b536-83005b8b5624,8354283
6-dc14-46c7-a6ce-1b485be51239,fe8d196c-2b2a-47cd-9c99-bd0d5851a733,09ae56ca-8a24-4f4a-a1d2-024de05e610c,983649b6-d1bd-4fff-b1f9-adfde60cfe2e,43758557-0568-4615-abbe-3b9926e1d46e: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\n","stdin":"{\"Pid\":3120232,\"Properties\":{\"app_id\":\"fcba7369-eae4-4dac-9292-d3f706577472\",\"org_id\":\
"12d0e6f0-ba0e-45f7-835e-d9304d92c64c\",\"policy_group_id\":\"fcba7369-eae4-4dac-9292-d3f706577472\",\"ports\":\"8080\",\"space_id\":\"2ba95e1a-0b54-4dfe-862e-6be8cbaaccfd\"},\"netout_rules\":[{\"networks\":[{\"start\":\"0.0.0.0\",\"end\":\"9.255.255.255\"}]},{\"networks\":[{\"start\":\"11.0.0.0\",\"end\":\"147.204.7.255\"}]},{\"networks\":[{\"start\":\"147.204.
9.0\",\"end\":\"155.56.54.155\"}]},{\"networks\":[{\"start\":\"155.56.54.159\",\"end\":\"155.56.68.227\"}]},{\"networks\":[{\"start\":\"155.56.68.230\",\"end\":\"155.56.68.235\"}]},{\"networks\":[{\"start\":\"155.56.68.238\",\"end\":\"169.253.255.255\"}]},{\"networks\":[{\"start\":\"169.255.0.0\",\"end\":\"172.15.255.255\"}]},{\"networks\":[{\"start\":\"172.32.0
.0\",\"end\":\"192.167.255.255\"}]},{\"networks\":[{\"start\":\"192.169.0.0\",\"end\":\"255.255.255.255\"}]},{\"protocol\":1,\"networks\":[{\"start\":\"10.0.0.0\",\"end\":\"10.255.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":2,\"networks\":[{\"start\":\"10.0.0.0\",\"end\":\"10.255.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol
\":1,\"networks\":[{\"start\":\"169.254.0.0\",\"end\":\"169.254.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":2,\"networks\":[{\"start\":\"169.254.0.0\",\"end\":\"169.254.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":1,\"networks\":[{\"start\":\"172.16.0.0\",\"end\":\"172.31.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]}
,{\"protocol\":2,\"networks\":[{\"start\":\"172.16.0.0\",\"end\":\"172.31.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":1,\"networks\":[{\"start\":\"192.168.0.0\",\"end\":\"192.168.255.255\"}],\"ports\":[{\"start\":53,\"end\":53}]},{\"protocol\":2,\"networks\":[{\"start\":\"192.168.0.0\",\"end\":\"192.168.255.255\"}],\"ports\":[{\"start\":53,\
"end\":53}]}],\"netin\":[{\"host_port\":0,\"container_port\":8080},{\"host_port\":0,\"container_port\":2222}]}","stdout":""}}
```
The http timeout seems hardcoded to 5s.

https://github.com/cloudfoundry/silk-release/blob/5dc42dd12d4ecc46c826c5a966f1cebbba734fc8/src/silk-daemon-bootstrap/main.go#L23

**Comment by tylerschultz** [comment]
What version of cf-networking & silk were you using?
Would you be able to share any information on your database? How much cpu and memory? 
Are you able to share any stats like open db connections?
What have you set the max_open_connections, max_idle_connections, and connections_max_lifetime_seconds (if available in the version you have deployed)?

**Comment by tylerschultz** [comment]
Hi @achawki,

FYI - We have a document here that details non DB related problems and solutions that were encountered by others who were attempting to run a large deployment: https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/large_deployments.md

Captain obvious here, but it seems you'll need a larger DB instance to get through these upgrades, at least in the short term. Perhaps with more data, we can form a strategy to reduce DB queries during an upgrade.

How many diego-cells are you updating at a time? perhaps a lower max_in_flight would help to reduce the load spike. We see that cf-deployment has it set to 1.

We're looking forward to seeing the metrics you gather from your next attempt.

@tylerschultz & @christianang

**Comment by ameowlia** [comment]
Hi @achawki, 

Is `policy-server-internal/properties/max_open_connections: 20` a typo? 

If you have 1000 diego-cells, and `policy_poll_interval_seconds` set to 300, that means that **on average** the internal policy server is getting 3+ requests per second from vxlan poliy agents on diego-cells. The vxlan policy agent then goes on to open a connection to the db. 

To reiterate what @tylerschultz and @christianang mentioned above, I don't think the **average case** is what is happening though. With a `max_in_flight` set to 50, it's likely that each group of 50 diego-cells come online at approximately the same time.  Meaning that all of the vxlan policy agents on those diego-cells will send a request to the internal policy server internal at the same time. 

[In our spec file, we recommend](https://github.com/cloudfoundry/cf-networking-release/blob/develop/jobs/policy-server-internal/spec#L72-L83) that an environment with 300 cells should set the `policy-server-internal/properties/max_open_connections` to ~200. Since you have 1000 cells, I would expect you would need this number to be higher.

- Amelia & @XanderStrike, CF Container Networking Team Members

**Comment by achawki** [comment]
Hi,

@tylerschultz thanks. 
- We were facing Problem 2 as well. 
- We had to increase the `lease_poll_interval_seconds` from described Problem 1 also, but we didn't see high cpu usage on cells. 
- We had to also increase the ulimit of the `diego-api` since the default of a bosh managed vm is 1024 (we used https://github.com/pivotal-cf/ulimit-release). 
- We had also to increase https://github.com/cloudfoundry/silk-release/blob/b949495e16b6c3acab765e139408a5db57fa27c0/jobs/silk-controller/spec#L33 since the default only allows for 250 cells.
- Not sure if this is worth mentioning in the document

We will provide more information as soon as we do another attempt with a newer `cf-networking-release` version. We will also then try with a larger database.

`max_in_flight` is set to 50. Reducing this value would definitely improve the situation, but would also lead to a significantly higher update duration. 

@ameowlia no we have indeed 20 max connections for the `policy-server-internal`. We first tried with the default configuration, but the landscape was in a broken state afterwards since the db ran out of connections.

`max_open_connections` for the `policy-server-internal` of 200 for each api node would mean `8000` connections + the connections of the `policy-server`.

I am by far not a postgres expert, but as far as I know, the connections of a postgres DB should not exceed 1000 if possible, even when having a larger DB `instance_type` (e.g. on GCP Cloud SQL even with the largest available postgres db size you get maximum 500 connections).

So we came up with 20 for our installation. The `policy-server-internal` seems to be more important since it might lead to push failures.
`20 * 40 + 5 * 40 =1000` (which is theoretically too high since 3 connections are reserved for the superuser)

**Comment by ameowlia** [comment]
Thanks @achawki, 

I have updated our [large deployment docs](https://github.com/cloudfoundry/silk-release/blob/b949495e16b6c3acab765e139408a5db57fa27c0/jobs/silk-controller/spec#L31-L33) to include the too small overlay ip for 250+ diego-cells problem and solution. 

Let us know when you try again and get more info. 

I'm excited to have you all running our code (or attempting to) at this scale! 🎉 

Best, 
Amelia, CF Container Networking Team Member

**Comment by achawki** [comment]
@tylerschultz @ameowlia 
We repeated the experiment to trigger an cell update with `max_in_flight` with 1000 cells, 30k apps and 4k policies.

This time with:
cf-deployment: `v6.5.0`
cf-networking-release:`2.19.0`
silk-release: `2.19.0`

First attempt with small database `db.t2.medium` in order to reproduce the issue with a newer version of cf-deployment.
* We couldn't see apps crashing this time.
* In the attached screenshot below it can be seen that the query max duration exceeds 5s duration during the update. Timeouts can be also seen in the logs, but somehow no apps crashed.
* All panels are stacked expect for the query max duration and InternalPoliciesRequestTime

![update_with_small_db](https://user-images.githubusercontent.com/16102838/50480403-1584f180-09dc-11e9-8189-567ba4d789ee.png)
![query_duration_smalll_db](https://user-images.githubusercontent.com/16102838/50480401-10c03d80-09dc-11e9-8445-42e3e2a09e5e.png)
![small_db_internalpoliciesrequesttime](https://user-images.githubusercontent.com/16102838/50481077-ecfef680-09df-11e9-9b73-ef25ee8f55a9.png)

Second attempt with larger database `db.t2.xlarge` (4 cpus 16gb memory)
* No apps crashed
* No timeouts could be seen in the logs. Max query duration stayed below 5s.
* All panels are stacked expect for the query max duration and InternalPoliciesRequestTime

![update_large_db](https://user-images.githubusercontent.com/16102838/50480557-e753e180-09dc-11e9-8245-d40f21bb035c.png)
![query_duration_largedb](https://user-images.githubusercontent.com/16102838/50480560-e91da500-09dc-11e9-9584-5757fbe05483.png)
![internalpoliciesrequesttime_largedb](https://user-images.githubusercontent.com/16102838/50481003-85e14200-09df-11e9-927c-0a0abdab1f56.png)

So a larger db indeed solved the issue, but we were also not able to reproduce the original issue anymore.

Not sure if it still might make sense to have the http timeout for the internal policy server configurable. This would leave more room in case of overload situation and for deployments where the exposed `poll_interval` has been adjusted.

Leaving the issue open for discussion, but feel free to close it.
