### ISSUE TITLE
Setup VPN connectivity for cf apps

### ISSUE THREAD

**Issue by epiard13** [cloudfoundry/cf-networking-release#62]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

As a platform operator I want to be able to connect applications of a specific
space to a private customer network using a VPN solution (e.g. ipsec, openvpn).

Is there any discussion/proposal/design document on that direction?
What do you think?

## Context

As a platform operator I want to be able to connect applications of a specific
space to a private customer network using a VPN solution (e.g. ipsec, openvpn).

Is there any discussion/proposal/design document on that direction?
What do you think?

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by tylerschultz** [comment]
Hi @epiard13, 

Thanks for submitting your feature inquiry. We have had an inquiry much like this before: https://github.com/cloudfoundry/cf-networking-release/issues/35

We have not made any plans or features in regards to this feature set.

Perhaps you can connect with our PM, Jonathan Sirlin @jsirlin to discuss in more depth what you're looking for. He can also be reached on the [Cloud Foundry Slack](cloudfoundry.slack.com) in the #container-networking channel.

**Comment by epiard13** [comment]
@tylerschultz,
Thanks

**Comment by barakyo** [comment]
Hi @epiard13, 

For a work around, I would recommend looking at the replies in the issue https://github.com/cloudfoundry/cf-networking-release/issues/35. In that issue, @rosenhouse talks about the possibility of creating your own CNI plugin to do custom networking things.

If you could provide us more details about what you are trying to do and why, it would help us be able to suggest other possible solutions.

Feel free to re-open if you have more questions. 

Thanks, 
@ameowlia and @barakyo, CF Networking Program Members
