### ISSUE TITLE
release components don't support Postgres with SSL required

### ISSUE THREAD

**Issue by thomasmitchell** [cloudfoundry/cf-networking-release#71]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

policy-server does not support connecting to a PostgreSQL database that requires TLS.

## Context

Any service using https://github.com/cloudfoundry/cf-networking-helpers for its db library is impacted by this. In this case, migratedb (in the pre-start for policyserver fails). This is due to `sslmode=disable` being hard-coded in the connection string for postgres (but not for mysql). Therefore, policy-server using postgres ignores the database tls configuration options that can be specified in the manifest spec.

I tested this using an Azure Database for PostgreSQL with SSL required.

## Steps to Reproduce

Make a Postgres server that requires ssl.
Specify database.require_ssl and database.ca_cert in your deployment manifest.
Check out /var/vcap/sys/log/policy-server/pre-start.stdout.log

## Expected result

[describe what you would expect to have resulted from this process]
I expected the deployment to succeed by connecting to the database.

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]
It fails with a complaint that the server requires SSL, but the client does not have any SSL settings configured.

[include relevant logs]
Fails with:
db connect: unable to ping: pq: SSL connection is required. Please specify SSL options and retry.

## Possible Fix

This line appears to be the smoking gun.

https://github.com/cloudfoundry/cf-networking-helpers/blob/671c7b0535ed7bde1fa9e4b7a3c38f3e9dbc8798/db/config.go#L28

The hardcoded sslmode=disable needs to be replaced with settings that set the sslmode and potentially specify the CA cert (the sslrootcert value).

**Comment by KauzClay** [comment]
Hi @thomasmitchell , 

This seems like a problem worth fixing. 

@adobley how does this look in terms of priority?

Thanks, 
@KauzClay  and @tcdowney , CF Networking Program Members
